---
- name: Install Nginx and PHP on Ubuntu
  hosts: webservers
  become: yes
  tasks:
    - name: Update apt repository cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Nginx
      ansible.builtin.apt:
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Install PHP and required extensions
      ansible.builtin.apt:
        name:
          - php
          - php-fpm
          - php-mysql
          - php-gd
          - php-curl
        state: present

    - name: Ensure PHP-FPM is started and enabled
      ansible.builtin.service:
        name: php7.4-fpm
        state: started
        enabled: yes