---
# tasks file for nginx
- name: Update apt repository cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: latest

  notify:
    - restart nginx

handlers:
  - name: restart nginx
    service: name=nginx state=reloaded