---
- hosts: database
- name: database assignment
  ansible.builtin.import_playbook: ../static-assignments/database.yml

- hosts: webservers
- name: webserver assignment
  ansible.builtin.import_playbook: ../static-assignments/nginx.yml